module.exports = {
  testEnvironment: 'node',
  globalSetup: '<rootDir>/jest.global-setup.js',
  roots: ['<rootDir>/src'],
  testMatch: [
    '<rootDir>/src/**/*.spec.ts',
    '<rootDir>/src/**/*.test.ts',
    '<rootDir>/src/**/*.spec.js',
    '<rootDir>/src/**/*.test.js',
    '<rootDir>/src/**/*.spec.tsx',
    '<rootDir>/src/**/*.test.tsx',
    '<rootDir>/src/**/*.spec.jsx',
    '<rootDir>/src/**/*.test.jsx',
  ],
  transform: {
    '^.+\\.(controller|module)\\.ts$': 'ts-jest',
    '^.+\\.(ts|js)$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/src/**/*.{ts,tsx}', '!<rootDir>/src/main.ts'],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  transformIgnorePatterns: ['/node_modules/'],
};